openapi: 3.0.0
info:
  title: datosYBioXNombre
  description: |
    Servicio rest que consulta datos y biométricos del cliente mediante el nombre entrada.
    Content-Type: application/x-www-form-urlencoded
  version: 1.0.0
servers:
  - url: https://tuservidor.com/ServiciosIDGuatemala/ConsultaV2
paths:
  /datosYBioXNombre:
    post:
      summary: Consulta datos y biométricos por nombre
      description: Endpoint que recibe parámetros para obtener información del cliente
      parameters:
        - name: ipAutenticacion
          in: query
          required: true
          schema:
            type: string
          description: Ip de donde se consumirá el servicio. Ejemplo: ipAutenticacion=ip desde donde consumiran
        - name: usuarioAutenticacion
          in: query
          required: true
          schema:
            type: string
          description: Usuario asignado. Ejemplo: usuarioAutenticacion=usuario asignado
        - name: nombre
          in: query
          required: true
          schema:
            type: string
            maxLength: 50
          description: Nombre del cliente. Ejemplo: Nombre=IRMA PATRICIA
        - name: apellidoPaterno
          in: query
          required: true
          schema:
            type: string
            maxLength: 50
          description: Apellido paterno del cliente. Ejemplo: apellidoPaterno=DE LA LUZ
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
        '400':
          description: Error en la solicitud
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
